[package]
name = "ow_blob_codec"
version = "0.1.1"
edition = "2021"
description = "Convert xml files to EIP4844 BLOB"
license = "MIT"

[dependencies]
c-kzg = "2.0.0"
miniz_oxide = "0.8.0"
quick-xml = "0.36.2"
