[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres-graph/graph-node"
pool_size = 10


[chains]
ingestor = "block_ingestor_node"
[chains.kurtosis]
shard = "primary"
provider = [
    { label = "kurtosis", url = "http://172.17.0.1:32769", features = [
    ] },
]


[deployment]
[[deployment.rule]]
indexers = ["index_node_0"]
