[package]
name = "ow_data_provider_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.3.6", features = ["full"] }
c-kzg = "1.0.3"
dotenvy = "0.15.7"
ow_blob_codec = "0.1.1"
tokio = { version = "1.40.0", features = ["full"] }
